name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        # and run on both Linux and Windows
        os: [ ubuntu-20.04, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
